### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [lenoreostrander/prj-rev-bwfs-tea-cozy#4]
(Meets Expectations) Overall, nice job.

Remember to indent nested html elements, as this improves the readability of our code. Also, avoid naming your files after their filetype and combine like styles by selecting multiple elements.

Otherwise, good use anchor links to link to sections on the page and nice use of semantic html elements! Well done!

**Comment by lenoreostrander** [comment]
I feel like I could do better when it comes to positioning since it took me hours to figure out how to build over an image and create a duplicate look for project but i learned a lot in my frustration
